on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: API Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.1.1
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          docker_name: 'owasp/zap2docker-stable'
          format: openapi
          target: 'https://dev.to/'
          cmd_options: '-a'
